Name:           ros-kinetic-jsk-teleop-joy
Version:        0.1.14
Release:        0%{?dist}
Summary:        ROS jsk_teleop_joy package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/jsk_teleop_joy
Source0:        %{name}-%{version}.tar.gz

Requires:       pygame-devel
Requires:       ros-kinetic-diagnostic-msgs
Requires:       ros-kinetic-diagnostic-updater
Requires:       ros-kinetic-image-view2
Requires:       ros-kinetic-interactive-markers
Requires:       ros-kinetic-joy-mouse
Requires:       ros-kinetic-jsk-footstep-msgs
Requires:       ros-kinetic-jsk-interactive-marker
Requires:       ros-kinetic-jsk-rviz-plugins
Requires:       ros-kinetic-ps3joy
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-view-controller-msgs
Requires:       ros-kinetic-visualization-msgs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-diagnostic-msgs
BuildRequires:  ros-kinetic-diagnostic-updater
BuildRequires:  ros-kinetic-interactive-markers
BuildRequires:  ros-kinetic-joy-mouse
BuildRequires:  ros-kinetic-jsk-footstep-msgs
BuildRequires:  ros-kinetic-jsk-interactive-marker
BuildRequires:  ros-kinetic-jsk-rviz-plugins
BuildRequires:  ros-kinetic-ps3joy
BuildRequires:  ros-kinetic-tf
BuildRequires:  ros-kinetic-view-controller-msgs
BuildRequires:  ros-kinetic-visualization-msgs

%description
jsk_teleop_joy

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Jan 15 2018 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 0.1.14-0
- Autogenerated by Bloom

* Tue Apr 18 2017 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 0.1.13-0
- Autogenerated by Bloom

* Wed Feb 22 2017 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 0.1.12-0
- Autogenerated by Bloom

* Tue Feb 14 2017 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 0.1.11-2
- Autogenerated by Bloom

