Name:           ros-hydro-jsk-footstep-controller
Version:        0.1.5
Release:        0%{?dist}
Summary:        ROS jsk_footstep_controller package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-diagnostic-msgs
Requires:       ros-hydro-diagnostic-updater
Requires:       ros-hydro-genmsg
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-jsk-footstep-msgs
Requires:       ros-hydro-jsk-footstep-planner
Requires:       ros-hydro-jsk-pcl-ros
Requires:       ros-hydro-jsk-topic-tools
Requires:       ros-hydro-message-filters
Requires:       ros-hydro-message-generation
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-tf
Requires:       ros-hydro-tf-conversions
Requires:       ros-hydro-tf2
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-diagnostic-msgs
BuildRequires:  ros-hydro-diagnostic-updater
BuildRequires:  ros-hydro-genmsg
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-jsk-footstep-msgs
BuildRequires:  ros-hydro-jsk-footstep-planner
BuildRequires:  ros-hydro-jsk-pcl-ros
BuildRequires:  ros-hydro-jsk-topic-tools
BuildRequires:  ros-hydro-message-filters
BuildRequires:  ros-hydro-message-generation
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-tf
BuildRequires:  ros-hydro-tf-conversions
BuildRequires:  ros-hydro-tf2

%description
The jsk_footstep_controller package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Jan 08 2015 Ryohei Ueda <garaemon@gmail.com> - 0.1.5-0
- Autogenerated by Bloom

* Sat Oct 11 2014 Ryohei Ueda <garaemon@gmail.com> - 0.1.3-0
- Autogenerated by Bloom

* Thu Sep 04 2014 Ryohei Ueda <garaemon@gmail.com> - 0.1.1-0
- Autogenerated by Bloom

