robot_command_buttons:
  - name: "Reset Walking Pose"
    type: emptysrv
    srv: "/footstep_command/reset_walking_pose"
  - name: "Reset Pose"
    type: emptysrv
    srv: "/footstep_command/reset_pose"
  - name: "Start ABC"
    type: emptysrv
    srv: "/footstep_command/start_abc"
