analogs:
- !!python/tuple [176, 20]
- !!python/tuple [176, 21]
- !!python/tuple [224, 9]
- !!python/tuple [176, 1]
- !!python/tuple [144, 61]
- !!python/tuple [144, 69]
- !!python/tuple [144, 65]
- !!python/tuple [144, 63]
- !!python/tuple [144, 60]
- !!python/tuple [144, 59]
- !!python/tuple [144, 57]
- !!python/tuple [144, 55]
- !!python/tuple [144, 49]
- !!python/tuple [144, 51]
- !!python/tuple [144, 68]
- !!python/tuple [144, 56]
- !!python/tuple [144, 48]
- !!python/tuple [144, 52]
- !!python/tuple [144, 54]
- !!python/tuple [144, 58]
- !!python/tuple [192, 0]
device_name: padKONTROL MIDI 2
